import { initDatabase, query } from '../config/database.js';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, '../../../.env') });

const seedCodeReviews = async () => {
  const items = [
    { title: 'User Authentication Module', description: 'Review login/logout functionality', code_snippet: 'async function login(email, password) {\n  const user = await User.findOne({ email });\n  if (!user) throw new Error("User not found");\n  const valid = await bcrypt.compare(password, user.password);\n  return valid ? generateToken(user) : null;\n}', language: 'javascript', status: 'completed', review_result: 'Good implementation with proper async/await. Consider adding rate limiting.' },
    { title: 'Shopping Cart Logic', description: 'E-commerce cart operations review', code_snippet: 'class Cart {\n  addItem(product, qty) {\n    const existing = this.items.find(i => i.id === product.id);\n    if (existing) existing.qty += qty;\n    else this.items.push({ ...product, qty });\n  }\n}', language: 'javascript', status: 'pending' },
    { title: 'Database Query Optimization', description: 'Review SQL queries for performance', code_snippet: 'SELECT u.*, o.* FROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nWHERE u.created_at > NOW() - INTERVAL 30 DAY;', language: 'sql', status: 'completed', review_result: 'Consider adding indexes on created_at and user_id columns.' },
    { title: 'React Form Validation', description: 'Form handling and validation review', code_snippet: 'const handleSubmit = (e) => {\n  e.preventDefault();\n  if (!email.includes("@")) {\n    setError("Invalid email");\n    return;\n  }\n  submitForm({ email, password });\n};', language: 'javascript', status: 'pending' },
    { title: 'File Upload Handler', description: 'Secure file upload implementation', code_snippet: 'app.post("/upload", multer({ dest: "uploads/" }).single("file"), (req, res) => {\n  if (!req.file) return res.status(400).send("No file");\n  res.json({ filename: req.file.filename });\n});', language: 'javascript', status: 'completed', review_result: 'Add file type validation and size limits for security.' },
    { title: 'WebSocket Connection Manager', description: 'Real-time communication handler', code_snippet: 'io.on("connection", (socket) => {\n  console.log("Client connected");\n  socket.on("message", (data) => {\n    io.emit("broadcast", data);\n  });\n});', language: 'javascript', status: 'pending' },
    { title: 'Password Hashing Utility', description: 'Cryptographic password handling', code_snippet: 'const hashPassword = async (password) => {\n  const salt = await bcrypt.genSalt(10);\n  return bcrypt.hash(password, salt);\n};', language: 'javascript', status: 'completed', review_result: 'Salt rounds of 10 is adequate. Consider making it configurable.' },
    { title: 'API Rate Limiter', description: 'Request throttling middleware', code_snippet: 'const rateLimiter = rateLimit({\n  windowMs: 15 * 60 * 1000,\n  max: 100,\n  message: "Too many requests"\n});', language: 'javascript', status: 'pending' },
    { title: 'Data Pagination Helper', description: 'List pagination implementation', code_snippet: 'function paginate(array, page, limit) {\n  const start = (page - 1) * limit;\n  return {\n    data: array.slice(start, start + limit),\n    total: array.length,\n    pages: Math.ceil(array.length / limit)\n  };\n}', language: 'javascript', status: 'completed', review_result: 'Clean implementation. Consider adding input validation.' },
    { title: 'JWT Token Generator', description: 'Token creation and validation', code_snippet: 'const generateToken = (user) => {\n  return jwt.sign(\n    { id: user.id, email: user.email },\n    process.env.JWT_SECRET,\n    { expiresIn: "24h" }\n  );\n};', language: 'javascript', status: 'pending' },
    { title: 'Error Boundary Component', description: 'React error handling', code_snippet: 'class ErrorBoundary extends Component {\n  state = { hasError: false };\n  static getDerivedStateFromError() {\n    return { hasError: true };\n  }\n  render() {\n    return this.state.hasError ? <Fallback /> : this.props.children;\n  }\n}', language: 'javascript', status: 'completed', review_result: 'Good error boundary. Add error logging service integration.' },
    { title: 'Caching Layer Implementation', description: 'Redis caching strategy', code_snippet: 'const getFromCache = async (key) => {\n  const cached = await redis.get(key);\n  if (cached) return JSON.parse(cached);\n  const data = await fetchFromDB(key);\n  await redis.setex(key, 3600, JSON.stringify(data));\n  return data;\n};', language: 'javascript', status: 'pending' },
    { title: 'Input Sanitization Middleware', description: 'XSS prevention utility', code_snippet: 'const sanitize = (req, res, next) => {\n  for (let key in req.body) {\n    if (typeof req.body[key] === "string") {\n      req.body[key] = xss(req.body[key].trim());\n    }\n  }\n  next();\n};', language: 'javascript', status: 'completed', review_result: 'Good XSS prevention. Consider recursive sanitization for nested objects.' },
    { title: 'Database Connection Pool', description: 'Connection management setup', code_snippet: 'const pool = new Pool({\n  host: process.env.DB_HOST,\n  max: 20,\n  idleTimeoutMillis: 30000,\n  connectionTimeoutMillis: 2000\n});', language: 'javascript', status: 'pending' },
    { title: 'Event Emitter Service', description: 'Custom event handling system', code_snippet: 'class EventBus {\n  constructor() {\n    this.events = {};\n  }\n  on(event, callback) {\n    if (!this.events[event]) this.events[event] = [];\n    this.events[event].push(callback);\n  }\n  emit(event, data) {\n    this.events[event]?.forEach(cb => cb(data));\n  }\n}', language: 'javascript', status: 'completed', review_result: 'Clean implementation. Consider adding once() and off() methods.' }
  ];

  for (const item of items) {
    await query(
      `INSERT INTO code_reviews (title, description, code_snippet, language, status, review_result)
       VALUES ($1, $2, $3, $4, $5, $6)`,
      [item.title, item.description, item.code_snippet, item.language, item.status, item.review_result || null]
    );
  }
  console.log('Seeded code_reviews');
};

const seedDocumentation = async () => {
  const items = [
    { title: 'User Service Documentation', description: 'User management service docs', source_code: 'class UserService {\n  async createUser(data) { /* ... */ }\n  async updateUser(id, data) { /* ... */ }\n  async deleteUser(id) { /* ... */ }\n}', doc_type: 'API', language: 'javascript', status: 'completed', generated_docs: '# UserService\n\n## Methods\n- createUser(data): Creates a new user\n- updateUser(id, data): Updates existing user\n- deleteUser(id): Removes user from system' },
    { title: 'Authentication Module Docs', description: 'Auth flow documentation', source_code: 'async function authenticate(credentials) {\n  const user = await validateCredentials(credentials);\n  return generateSession(user);\n}', doc_type: 'Module', language: 'javascript', status: 'pending' },
    { title: 'Payment Gateway Integration', description: 'Payment processing docs', source_code: 'class PaymentGateway {\n  async charge(amount, card) { /* ... */ }\n  async refund(transactionId) { /* ... */ }\n}', doc_type: 'Integration', language: 'javascript', status: 'completed', generated_docs: '# PaymentGateway\n\nSecure payment processing integration.\n\n## Methods\n- charge(amount, card): Process payment\n- refund(transactionId): Process refund' },
    { title: 'Database Models Documentation', description: 'ORM model definitions', source_code: 'const UserModel = {\n  tableName: "users",\n  fields: ["id", "email", "password", "created_at"]\n};', doc_type: 'Schema', language: 'javascript', status: 'pending' },
    { title: 'Middleware Stack Docs', description: 'Express middleware documentation', source_code: 'app.use(cors());\napp.use(helmet());\napp.use(express.json());\napp.use(rateLimiter);', doc_type: 'Configuration', language: 'javascript', status: 'completed', generated_docs: '# Middleware Stack\n\n1. CORS - Cross-origin requests\n2. Helmet - Security headers\n3. JSON Parser - Body parsing\n4. Rate Limiter - Request throttling' },
    { title: 'Utility Functions Library', description: 'Helper functions docs', source_code: 'export const formatDate = (date) => { /* ... */ };\nexport const slugify = (text) => { /* ... */ };\nexport const debounce = (fn, delay) => { /* ... */ };', doc_type: 'Library', language: 'javascript', status: 'pending' },
    { title: 'React Hooks Documentation', description: 'Custom hooks reference', source_code: 'function useLocalStorage(key, initialValue) {\n  const [value, setValue] = useState(() => {\n    return localStorage.getItem(key) || initialValue;\n  });\n  return [value, setValue];\n}', doc_type: 'Hooks', language: 'javascript', status: 'completed', generated_docs: '# useLocalStorage\n\nPersists state in localStorage.\n\n## Parameters\n- key: Storage key\n- initialValue: Default value\n\n## Returns\n[value, setValue] tuple' },
    { title: 'API Client Documentation', description: 'HTTP client wrapper', source_code: 'const apiClient = {\n  get: (url) => fetch(url).then(r => r.json()),\n  post: (url, data) => fetch(url, { method: "POST", body: JSON.stringify(data) })\n};', doc_type: 'Client', language: 'javascript', status: 'pending' },
    { title: 'Validation Schema Docs', description: 'Input validation schemas', source_code: 'const userSchema = Joi.object({\n  email: Joi.string().email().required(),\n  password: Joi.string().min(8).required()\n});', doc_type: 'Validation', language: 'javascript', status: 'completed', generated_docs: '# User Validation Schema\n\n## Fields\n- email: Required, must be valid email\n- password: Required, minimum 8 characters' },
    { title: 'Logger Service Documentation', description: 'Logging infrastructure', source_code: 'const logger = {\n  info: (msg) => console.log(`[INFO] ${msg}`),\n  error: (msg) => console.error(`[ERROR] ${msg}`),\n  debug: (msg) => console.debug(`[DEBUG] ${msg}`)\n};', doc_type: 'Service', language: 'javascript', status: 'pending' },
    { title: 'State Management Docs', description: 'Redux store documentation', source_code: 'const store = configureStore({\n  reducer: { user: userReducer, cart: cartReducer },\n  middleware: [thunk, logger]\n});', doc_type: 'Store', language: 'javascript', status: 'completed', generated_docs: '# Redux Store\n\n## Reducers\n- user: User state management\n- cart: Shopping cart state\n\n## Middleware\n- thunk: Async actions\n- logger: Action logging' },
    { title: 'WebSocket Events Docs', description: 'Real-time event reference', source_code: 'socket.on("connect", onConnect);\nsocket.on("message", onMessage);\nsocket.on("disconnect", onDisconnect);', doc_type: 'Events', language: 'javascript', status: 'pending' },
    { title: 'CLI Commands Documentation', description: 'Command line interface', source_code: 'program\n  .command("build")\n  .description("Build the project")\n  .action(buildCommand);', doc_type: 'CLI', language: 'javascript', status: 'completed', generated_docs: '# CLI Commands\n\n## build\nBuilds the project for production.\n\nUsage: `cli build`' },
    { title: 'Test Utilities Docs', description: 'Testing helper functions', source_code: 'const renderWithProviders = (ui) => {\n  return render(<Providers>{ui}</Providers>);\n};', doc_type: 'Testing', language: 'javascript', status: 'pending' },
    { title: 'Configuration Module Docs', description: 'App configuration reference', source_code: 'const config = {\n  port: process.env.PORT || 3000,\n  dbUrl: process.env.DATABASE_URL,\n  apiKey: process.env.API_KEY\n};', doc_type: 'Config', language: 'javascript', status: 'completed', generated_docs: '# Configuration\n\n## Environment Variables\n- PORT: Server port (default: 3000)\n- DATABASE_URL: Database connection string\n- API_KEY: External API key' }
  ];

  for (const item of items) {
    await query(
      `INSERT INTO documentation (title, description, source_code, doc_type, language, status, generated_docs)
       VALUES ($1, $2, $3, $4, $5, $6, $7)`,
      [item.title, item.description, item.source_code, item.doc_type, item.language, item.status, item.generated_docs || null]
    );
  }
  console.log('Seeded documentation');
};

const seedCodeAnalysis = async () => {
  const items = [
    { title: 'Authentication Flow Analysis', description: 'Analyze auth module complexity', code_snippet: 'async function login(email, password) {\n  const user = await User.findOne({ email });\n  if (!user) throw new Error("Not found");\n  if (user.locked) throw new Error("Locked");\n  const valid = await bcrypt.compare(password, user.password);\n  if (!valid) {\n    user.failedAttempts++;\n    if (user.failedAttempts >= 5) user.locked = true;\n    await user.save();\n    throw new Error("Invalid");\n  }\n  return generateToken(user);\n}', language: 'javascript', complexity_score: 8, quality_score: 75, status: 'completed', analysis_result: 'Cyclomatic complexity: 8. Consider extracting validation logic.' },
    { title: 'Data Processing Pipeline', description: 'ETL process analysis', code_snippet: 'const processData = (data) => {\n  return data\n    .filter(item => item.active)\n    .map(item => transform(item))\n    .reduce((acc, item) => ({ ...acc, [item.id]: item }), {});\n};', language: 'javascript', complexity_score: 4, quality_score: 85, status: 'completed', analysis_result: 'Clean functional approach. Low complexity.' },
    { title: 'Form Validation Logic', description: 'Client-side validation analysis', code_snippet: 'function validateForm(data) {\n  const errors = {};\n  if (!data.email) errors.email = "Required";\n  else if (!isEmail(data.email)) errors.email = "Invalid";\n  if (!data.password) errors.password = "Required";\n  else if (data.password.length < 8) errors.password = "Too short";\n  return Object.keys(errors).length ? errors : null;\n}', language: 'javascript', complexity_score: 6, quality_score: 70, status: 'pending' },
    { title: 'API Response Handler', description: 'Response formatting analysis', code_snippet: 'const handleResponse = (res, data, status = 200) => {\n  res.status(status).json({\n    success: status < 400,\n    data: status < 400 ? data : null,\n    error: status >= 400 ? data : null,\n    timestamp: new Date().toISOString()\n  });\n};', language: 'javascript', complexity_score: 3, quality_score: 90, status: 'completed', analysis_result: 'Simple and effective. Consider adding pagination support.' },
    { title: 'Search Algorithm Implementation', description: 'Binary search analysis', code_snippet: 'function binarySearch(arr, target) {\n  let left = 0, right = arr.length - 1;\n  while (left <= right) {\n    const mid = Math.floor((left + right) / 2);\n    if (arr[mid] === target) return mid;\n    if (arr[mid] < target) left = mid + 1;\n    else right = mid - 1;\n  }\n  return -1;\n}', language: 'javascript', complexity_score: 4, quality_score: 95, status: 'completed', analysis_result: 'Optimal O(log n) complexity. Well implemented.' },
    { title: 'State Management Reducer', description: 'Redux reducer analysis', code_snippet: 'const userReducer = (state = initialState, action) => {\n  switch (action.type) {\n    case "SET_USER": return { ...state, user: action.payload };\n    case "LOGOUT": return initialState;\n    case "UPDATE_PROFILE": return { ...state, user: { ...state.user, ...action.payload } };\n    default: return state;\n  }\n};', language: 'javascript', complexity_score: 5, quality_score: 80, status: 'pending' },
    { title: 'Async Queue Processor', description: 'Job queue analysis', code_snippet: 'class JobQueue {\n  constructor() { this.queue = []; this.processing = false; }\n  async add(job) {\n    this.queue.push(job);\n    if (!this.processing) await this.process();\n  }\n  async process() {\n    this.processing = true;\n    while (this.queue.length) {\n      const job = this.queue.shift();\n      await job();\n    }\n    this.processing = false;\n  }\n}', language: 'javascript', complexity_score: 6, quality_score: 75, status: 'completed', analysis_result: 'Good queue implementation. Add error handling for failed jobs.' },
    { title: 'Cache Invalidation Logic', description: 'Caching strategy analysis', code_snippet: 'const cache = new Map();\nconst getWithCache = async (key, fetchFn, ttl = 60000) => {\n  const cached = cache.get(key);\n  if (cached && Date.now() - cached.timestamp < ttl) return cached.data;\n  const data = await fetchFn();\n  cache.set(key, { data, timestamp: Date.now() });\n  return data;\n};', language: 'javascript', complexity_score: 4, quality_score: 85, status: 'pending' },
    { title: 'Permission Checker', description: 'RBAC analysis', code_snippet: 'const checkPermission = (user, resource, action) => {\n  const role = roles[user.role];\n  if (!role) return false;\n  const permissions = role.permissions[resource];\n  return permissions && permissions.includes(action);\n};', language: 'javascript', complexity_score: 4, quality_score: 80, status: 'completed', analysis_result: 'Simple RBAC. Consider adding hierarchical roles.' },
    { title: 'Data Transformer Utility', description: 'Object transformation analysis', code_snippet: 'const transformUser = (dbUser) => ({\n  id: dbUser.id,\n  name: `${dbUser.first_name} ${dbUser.last_name}`,\n  email: dbUser.email,\n  joinedAt: formatDate(dbUser.created_at)\n});', language: 'javascript', complexity_score: 2, quality_score: 92, status: 'pending' },
    { title: 'Event Handler Module', description: 'Event system analysis', code_snippet: 'const EventHandler = {\n  handlers: {},\n  on(event, fn) { (this.handlers[event] ||= []).push(fn); },\n  off(event, fn) { this.handlers[event] = this.handlers[event]?.filter(f => f !== fn); },\n  emit(event, ...args) { this.handlers[event]?.forEach(fn => fn(...args)); }\n};', language: 'javascript', complexity_score: 5, quality_score: 85, status: 'completed', analysis_result: 'Clean pub/sub pattern. Consider adding once() method.' },
    { title: 'Middleware Chain', description: 'Express middleware analysis', code_snippet: 'const authMiddleware = (req, res, next) => {\n  const token = req.headers.authorization?.split(" ")[1];\n  if (!token) return res.status(401).json({ error: "No token" });\n  try {\n    req.user = jwt.verify(token, SECRET);\n    next();\n  } catch { res.status(401).json({ error: "Invalid token" }); }\n};', language: 'javascript', complexity_score: 5, quality_score: 78, status: 'pending' },
    { title: 'Query Builder', description: 'SQL builder analysis', code_snippet: 'class QueryBuilder {\n  constructor(table) { this.table = table; this.conditions = []; }\n  where(field, value) { this.conditions.push(`${field} = ${value}`); return this; }\n  build() { return `SELECT * FROM ${this.table} WHERE ${this.conditions.join(" AND ")}`; }\n}', language: 'javascript', complexity_score: 3, quality_score: 70, status: 'completed', analysis_result: 'SQL injection risk! Use parameterized queries.' },
    { title: 'Retry Mechanism', description: 'Fault tolerance analysis', code_snippet: 'const retry = async (fn, maxRetries = 3, delay = 1000) => {\n  for (let i = 0; i < maxRetries; i++) {\n    try { return await fn(); }\n    catch (e) { if (i === maxRetries - 1) throw e; await sleep(delay); }\n  }\n};', language: 'javascript', complexity_score: 4, quality_score: 82, status: 'pending' },
    { title: 'Config Loader', description: 'Configuration loading analysis', code_snippet: 'const loadConfig = () => {\n  const env = process.env.NODE_ENV || "development";\n  const base = require("./config.base.json");\n  const envConfig = require(`./config.${env}.json`);\n  return { ...base, ...envConfig };\n};', language: 'javascript', complexity_score: 3, quality_score: 75, status: 'completed', analysis_result: 'Good config merging. Consider using dotenv for sensitive values.' }
  ];

  for (const item of items) {
    await query(
      `INSERT INTO code_analysis (title, description, code_snippet, language, complexity_score, quality_score, status, analysis_result)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
      [item.title, item.description, item.code_snippet, item.language, item.complexity_score || null, item.quality_score || null, item.status, item.analysis_result || null]
    );
  }
  console.log('Seeded code_analysis');
};

const seedApiDocs = async () => {
  const items = [
    { title: 'Create User Endpoint', description: 'User registration API', endpoint: '/api/users', method: 'POST', request_body: '{ "email": "string", "password": "string", "name": "string" }', response_body: '{ "id": "number", "email": "string", "name": "string" }', status: 'completed', generated_docs: '# POST /api/users\n\nCreates a new user account.\n\n## Request Body\n- email: User email (required)\n- password: User password (required)\n- name: Display name (required)' },
    { title: 'Get User Profile', description: 'Fetch user details', endpoint: '/api/users/:id', method: 'GET', request_body: null, response_body: '{ "id": "number", "email": "string", "profile": {} }', status: 'pending' },
    { title: 'Update User Settings', description: 'Modify user preferences', endpoint: '/api/users/:id/settings', method: 'PUT', request_body: '{ "notifications": "boolean", "theme": "string" }', response_body: '{ "success": "boolean" }', status: 'completed', generated_docs: '# PUT /api/users/:id/settings\n\nUpdates user preferences.\n\n## Parameters\n- id: User ID\n\n## Request Body\n- notifications: Enable notifications\n- theme: UI theme preference' },
    { title: 'Delete Account', description: 'Remove user account', endpoint: '/api/users/:id', method: 'DELETE', request_body: null, response_body: '{ "message": "string" }', status: 'pending' },
    { title: 'Login Endpoint', description: 'User authentication', endpoint: '/api/auth/login', method: 'POST', request_body: '{ "email": "string", "password": "string" }', response_body: '{ "token": "string", "user": {} }', status: 'completed', generated_docs: '# POST /api/auth/login\n\nAuthenticates user and returns JWT token.\n\n## Request Body\n- email: User email\n- password: User password\n\n## Response\n- token: JWT access token\n- user: User object' },
    { title: 'List Products', description: 'Get all products', endpoint: '/api/products', method: 'GET', request_body: null, response_body: '{ "products": [], "total": "number", "page": "number" }', status: 'pending' },
    { title: 'Create Order', description: 'Place new order', endpoint: '/api/orders', method: 'POST', request_body: '{ "items": [], "shippingAddress": {} }', response_body: '{ "orderId": "string", "total": "number" }', status: 'completed', generated_docs: '# POST /api/orders\n\nCreates a new order.\n\n## Request Body\n- items: Array of order items\n- shippingAddress: Delivery address\n\n## Response\n- orderId: Unique order identifier\n- total: Order total amount' },
    { title: 'Get Order Status', description: 'Check order progress', endpoint: '/api/orders/:id/status', method: 'GET', request_body: null, response_body: '{ "status": "string", "updatedAt": "string" }', status: 'pending' },
    { title: 'Upload File', description: 'File upload endpoint', endpoint: '/api/files/upload', method: 'POST', request_body: 'multipart/form-data', response_body: '{ "fileId": "string", "url": "string" }', status: 'completed', generated_docs: '# POST /api/files/upload\n\nUploads a file to storage.\n\n## Request\nContent-Type: multipart/form-data\n\n## Response\n- fileId: Uploaded file ID\n- url: Public URL' },
    { title: 'Search Products', description: 'Product search API', endpoint: '/api/products/search', method: 'GET', request_body: null, response_body: '{ "results": [], "count": "number" }', status: 'pending' },
    { title: 'Add to Cart', description: 'Add item to cart', endpoint: '/api/cart/items', method: 'POST', request_body: '{ "productId": "string", "quantity": "number" }', response_body: '{ "cartId": "string", "items": [] }', status: 'completed', generated_docs: '# POST /api/cart/items\n\nAdds an item to shopping cart.\n\n## Request Body\n- productId: Product to add\n- quantity: Number of items\n\n## Response\n- cartId: Cart identifier\n- items: Updated cart items' },
    { title: 'Process Payment', description: 'Payment processing', endpoint: '/api/payments/charge', method: 'POST', request_body: '{ "amount": "number", "currency": "string", "source": "string" }', response_body: '{ "transactionId": "string", "status": "string" }', status: 'pending' },
    { title: 'Get Notifications', description: 'User notifications list', endpoint: '/api/notifications', method: 'GET', request_body: null, response_body: '{ "notifications": [], "unread": "number" }', status: 'completed', generated_docs: '# GET /api/notifications\n\nRetrieves user notifications.\n\n## Response\n- notifications: List of notifications\n- unread: Unread count' },
    { title: 'Refresh Token', description: 'Token refresh endpoint', endpoint: '/api/auth/refresh', method: 'POST', request_body: '{ "refreshToken": "string" }', response_body: '{ "accessToken": "string" }', status: 'pending' },
    { title: 'Health Check', description: 'API health status', endpoint: '/api/health', method: 'GET', request_body: null, response_body: '{ "status": "string", "version": "string" }', status: 'completed', generated_docs: '# GET /api/health\n\nReturns API health status.\n\n## Response\n- status: "ok" or "error"\n- version: API version' }
  ];

  for (const item of items) {
    await query(
      `INSERT INTO api_docs (title, description, endpoint, method, request_body, response_body, status, generated_docs)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
      [item.title, item.description, item.endpoint, item.method, item.request_body, item.response_body, item.status, item.generated_docs || null]
    );
  }
  console.log('Seeded api_docs');
};

const seedReadmeProjects = async () => {
  const items = [
    { title: 'E-Commerce Platform', description: 'Full-stack online store', project_structure: 'src/\n  components/\n  pages/\n  api/\n  utils/', tech_stack: 'React, Node.js, PostgreSQL, Redis', status: 'completed', generated_readme: '# E-Commerce Platform\n\nA modern e-commerce solution.\n\n## Features\n- Product catalog\n- Shopping cart\n- Secure checkout\n\n## Tech Stack\nReact, Node.js, PostgreSQL, Redis' },
    { title: 'Task Management App', description: 'Kanban-style task tracker', project_structure: 'app/\n  models/\n  views/\n  controllers/', tech_stack: 'Vue.js, Express, MongoDB', status: 'pending' },
    { title: 'Real-time Chat Application', description: 'WebSocket-based messaging', project_structure: 'client/\n  src/\nserver/\n  handlers/', tech_stack: 'React, Socket.io, Node.js', status: 'completed', generated_readme: '# Real-time Chat\n\nInstant messaging application.\n\n## Features\n- Private messaging\n- Group chats\n- File sharing' },
    { title: 'Blog Platform', description: 'Content management system', project_structure: 'posts/\nadmin/\napi/\nthemes/', tech_stack: 'Next.js, Prisma, PostgreSQL', status: 'pending' },
    { title: 'Weather Dashboard', description: 'Weather forecasting app', project_structure: 'components/\nservices/\nhooks/', tech_stack: 'React, OpenWeather API, Chart.js', status: 'completed', generated_readme: '# Weather Dashboard\n\nReal-time weather information.\n\n## Features\n- Current conditions\n- 7-day forecast\n- Interactive maps' },
    { title: 'Fitness Tracker', description: 'Health and workout app', project_structure: 'mobile/\nbackend/\nshared/', tech_stack: 'React Native, Node.js, MongoDB', status: 'pending' },
    { title: 'Invoice Generator', description: 'Business invoicing tool', project_structure: 'templates/\ngenerator/\npreview/', tech_stack: 'Python, Flask, WeasyPrint', status: 'completed', generated_readme: '# Invoice Generator\n\nProfessional invoicing solution.\n\n## Features\n- Custom templates\n- PDF export\n- Client management' },
    { title: 'Social Media Dashboard', description: 'Analytics aggregator', project_structure: 'integrations/\nanalytics/\nreports/', tech_stack: 'React, D3.js, Node.js', status: 'pending' },
    { title: 'Learning Management System', description: 'Online course platform', project_structure: 'courses/\nstudents/\ninstructors/\nassessments/', tech_stack: 'Django, React, PostgreSQL', status: 'completed', generated_readme: '# Learning Management System\n\nComprehensive e-learning platform.\n\n## Features\n- Course creation\n- Progress tracking\n- Assessments\n- Certificates' },
    { title: 'Inventory Management', description: 'Stock tracking system', project_structure: 'products/\norders/\nreports/\napi/', tech_stack: 'Vue.js, Laravel, MySQL', status: 'pending' },
    { title: 'Recipe Sharing App', description: 'Cooking community platform', project_structure: 'recipes/\nusers/\nsocial/\nsearch/', tech_stack: 'Next.js, Supabase', status: 'completed', generated_readme: '# Recipe Sharing\n\nCommunity cooking platform.\n\n## Features\n- Recipe sharing\n- Meal planning\n- Shopping lists\n- Social features' },
    { title: 'Portfolio Website', description: 'Personal portfolio template', project_structure: 'pages/\ncomponents/\nstyles/\ndata/', tech_stack: 'Astro, Tailwind CSS', status: 'pending' },
    { title: 'Event Management System', description: 'Event planning platform', project_structure: 'events/\ntickets/\nvendors/\nanalytics/', tech_stack: 'React, Express, PostgreSQL, Stripe', status: 'completed', generated_readme: '# Event Management\n\nComplete event planning solution.\n\n## Features\n- Event creation\n- Ticket sales\n- Vendor management\n- Attendee tracking' },
    { title: 'Project Management Tool', description: 'Team collaboration app', project_structure: 'projects/\ntasks/\nteams/\nreports/', tech_stack: 'Angular, NestJS, PostgreSQL', status: 'pending' },
    { title: 'API Gateway Service', description: 'Microservices gateway', project_structure: 'gateway/\nauth/\nrouting/\nmonitoring/', tech_stack: 'Go, Redis, Kubernetes', status: 'completed', generated_readme: '# API Gateway\n\nMicroservices API gateway.\n\n## Features\n- Request routing\n- Rate limiting\n- Authentication\n- Monitoring' }
  ];

  for (const item of items) {
    await query(
      `INSERT INTO readme_projects (title, description, project_structure, tech_stack, status, generated_readme)
       VALUES ($1, $2, $3, $4, $5, $6)`,
      [item.title, item.description, item.project_structure, item.tech_stack, item.status, item.generated_readme || null]
    );
  }
  console.log('Seeded readme_projects');
};

const seedCodeComments = async () => {
  const items = [
    { title: 'User Authentication Function', description: 'Add docstrings to auth logic', code_snippet: 'async function authenticateUser(email, password) {\n  const user = await User.findByEmail(email);\n  if (!user) return null;\n  const isValid = await comparePassword(password, user.hash);\n  return isValid ? createSession(user) : null;\n}', language: 'javascript', comment_style: 'JSDoc', status: 'completed', generated_comments: '/**\n * Authenticates a user with email and password\n * @param {string} email - User email address\n * @param {string} password - Plain text password\n * @returns {Promise<Session|null>} Session object or null if auth fails\n */\nasync function authenticateUser(email, password) {' },
    { title: 'Data Processing Pipeline', description: 'Document ETL functions', code_snippet: 'const processRecords = (records) => {\n  return records\n    .filter(r => r.active)\n    .map(r => transformRecord(r))\n    .reduce((acc, r) => [...acc, r], []);\n};', language: 'javascript', comment_style: 'inline', status: 'pending' },
    { title: 'React Custom Hook', description: 'Add hook documentation', code_snippet: 'function useDebounce(value, delay) {\n  const [debouncedValue, setDebouncedValue] = useState(value);\n  useEffect(() => {\n    const timer = setTimeout(() => setDebouncedValue(value), delay);\n    return () => clearTimeout(timer);\n  }, [value, delay]);\n  return debouncedValue;\n}', language: 'javascript', comment_style: 'JSDoc', status: 'completed', generated_comments: '/**\n * Custom hook that debounces a value\n * @param {any} value - The value to debounce\n * @param {number} delay - Debounce delay in milliseconds\n * @returns {any} The debounced value\n */\nfunction useDebounce(value, delay) {' },
    { title: 'Database Query Builder', description: 'Document query methods', code_snippet: 'class QueryBuilder {\n  select(fields) {\n    this.fields = fields;\n    return this;\n  }\n  where(condition) {\n    this.conditions.push(condition);\n    return this;\n  }\n  execute() {\n    return db.query(this.build());\n  }\n}', language: 'javascript', comment_style: 'JSDoc', status: 'pending' },
    { title: 'API Middleware Stack', description: 'Comment middleware functions', code_snippet: 'const validateRequest = (schema) => (req, res, next) => {\n  const { error } = schema.validate(req.body);\n  if (error) return res.status(400).json({ error: error.message });\n  next();\n};', language: 'javascript', comment_style: 'inline', status: 'completed', generated_comments: '/**\n * Creates validation middleware for request body\n * @param {Object} schema - Joi validation schema\n * @returns {Function} Express middleware function\n */\nconst validateRequest = (schema) => (req, res, next) => {\n  // Validate request body against schema\n  const { error } = schema.validate(req.body);' },
    { title: 'Event Emitter Class', description: 'Document event methods', code_snippet: 'class EventEmitter {\n  on(event, listener) {\n    this.listeners[event] = this.listeners[event] || [];\n    this.listeners[event].push(listener);\n  }\n  emit(event, data) {\n    this.listeners[event]?.forEach(fn => fn(data));\n  }\n}', language: 'javascript', comment_style: 'JSDoc', status: 'pending' },
    { title: 'File Upload Handler', description: 'Add upload documentation', code_snippet: 'const handleUpload = async (file, options = {}) => {\n  const { maxSize = 5MB, allowedTypes = ["image/*"] } = options;\n  if (file.size > maxSize) throw new Error("File too large");\n  if (!matchType(file.type, allowedTypes)) throw new Error("Invalid type");\n  return await storage.save(file);\n};', language: 'javascript', comment_style: 'JSDoc', status: 'completed', generated_comments: '/**\n * Handles file upload with validation\n * @param {File} file - The file to upload\n * @param {Object} options - Upload options\n * @param {number} options.maxSize - Maximum file size in bytes\n * @param {string[]} options.allowedTypes - Allowed MIME types\n * @returns {Promise<string>} Uploaded file URL\n * @throws {Error} If file exceeds size limit or type not allowed\n */' },
    { title: 'Cache Implementation', description: 'Document cache methods', code_snippet: 'const cache = {\n  store: new Map(),\n  get(key) { return this.store.get(key); },\n  set(key, value, ttl) {\n    this.store.set(key, { value, expires: Date.now() + ttl });\n  },\n  has(key) {\n    const item = this.store.get(key);\n    return item && item.expires > Date.now();\n  }\n};', language: 'javascript', comment_style: 'inline', status: 'pending' },
    { title: 'Redux Action Creators', description: 'Add action documentation', code_snippet: 'const fetchUser = (userId) => async (dispatch) => {\n  dispatch({ type: "FETCH_USER_START" });\n  try {\n    const user = await api.getUser(userId);\n    dispatch({ type: "FETCH_USER_SUCCESS", payload: user });\n  } catch (error) {\n    dispatch({ type: "FETCH_USER_ERROR", payload: error });\n  }\n};', language: 'javascript', comment_style: 'JSDoc', status: 'completed', generated_comments: '/**\n * Async action creator for fetching user data\n * @param {string} userId - The ID of the user to fetch\n * @returns {Function} Redux thunk function\n */\nconst fetchUser = (userId) => async (dispatch) => {' },
    { title: 'Form Validation Utils', description: 'Document validators', code_snippet: 'const validators = {\n  email: (value) => /^[^@]+@[^@]+\\.[^@]+$/.test(value),\n  minLength: (min) => (value) => value.length >= min,\n  required: (value) => value !== null && value !== undefined && value !== ""\n};', language: 'javascript', comment_style: 'JSDoc', status: 'pending' },
    { title: 'WebSocket Manager', description: 'Add connection documentation', code_snippet: 'class WebSocketManager {\n  connect(url) {\n    this.ws = new WebSocket(url);\n    this.ws.onopen = () => this.emit("connected");\n    this.ws.onmessage = (e) => this.emit("message", JSON.parse(e.data));\n    this.ws.onclose = () => this.reconnect();\n  }\n}', language: 'javascript', comment_style: 'JSDoc', status: 'completed', generated_comments: '/**\n * Manages WebSocket connections with auto-reconnect\n */\nclass WebSocketManager {\n  /**\n   * Establishes WebSocket connection\n   * @param {string} url - WebSocket server URL\n   */\n  connect(url) {' },
    { title: 'Date Formatting Utils', description: 'Document date helpers', code_snippet: 'const formatDate = (date, format = "YYYY-MM-DD") => {\n  const d = new Date(date);\n  return format\n    .replace("YYYY", d.getFullYear())\n    .replace("MM", String(d.getMonth() + 1).padStart(2, "0"))\n    .replace("DD", String(d.getDate()).padStart(2, "0"));\n};', language: 'javascript', comment_style: 'JSDoc', status: 'pending' },
    { title: 'Error Handler Middleware', description: 'Add error handling docs', code_snippet: 'const errorHandler = (err, req, res, next) => {\n  const status = err.status || 500;\n  const message = err.message || "Internal Server Error";\n  logger.error({ err, req });\n  res.status(status).json({ error: message });\n};', language: 'javascript', comment_style: 'inline', status: 'completed', generated_comments: '/**\n * Express error handling middleware\n * Logs errors and sends appropriate response\n * @param {Error} err - The error object\n * @param {Request} req - Express request\n * @param {Response} res - Express response\n * @param {Function} next - Next middleware\n */' },
    { title: 'Permission Checker', description: 'Document auth helpers', code_snippet: 'const hasPermission = (user, resource, action) => {\n  const role = roles[user.role];\n  if (!role) return false;\n  const perms = role.permissions[resource];\n  return perms?.includes(action) || perms?.includes("*");\n};', language: 'javascript', comment_style: 'JSDoc', status: 'pending' },
    { title: 'Pagination Helper', description: 'Add pagination docs', code_snippet: 'const paginate = (items, page = 1, perPage = 10) => {\n  const total = items.length;\n  const totalPages = Math.ceil(total / perPage);\n  const start = (page - 1) * perPage;\n  return {\n    data: items.slice(start, start + perPage),\n    meta: { page, perPage, total, totalPages }\n  };\n};', language: 'javascript', comment_style: 'JSDoc', status: 'completed', generated_comments: '/**\n * Paginates an array of items\n * @param {Array} items - Items to paginate\n * @param {number} page - Current page (1-indexed)\n * @param {number} perPage - Items per page\n * @returns {Object} Paginated data with metadata\n */' }
  ];

  for (const item of items) {
    await query(
      `INSERT INTO code_comments (title, description, code_snippet, language, comment_style, status, generated_comments)
       VALUES ($1, $2, $3, $4, $5, $6, $7)`,
      [item.title, item.description, item.code_snippet, item.language, item.comment_style, item.status, item.generated_comments || null]
    );
  }
  console.log('Seeded code_comments');
};

const seedSecurityScans = async () => {
  const items = [
    { title: 'User Input Handler', description: 'Check for injection vulnerabilities', code_snippet: 'app.get("/search", (req, res) => {\n  const query = req.query.q;\n  const sql = `SELECT * FROM products WHERE name LIKE "%${query}%"`;\n  db.query(sql, (err, results) => res.json(results));\n});', language: 'javascript', risk_level: 'critical', status: 'completed', vulnerabilities: 'SQL Injection vulnerability detected. User input directly concatenated into SQL query.', recommendations: 'Use parameterized queries or prepared statements.' },
    { title: 'Authentication Endpoint', description: 'Review auth security', code_snippet: 'app.post("/login", (req, res) => {\n  const { username, password } = req.body;\n  const user = users.find(u => u.username === username && u.password === password);\n  if (user) res.json({ token: btoa(user.id) });\n  else res.status(401).json({ error: "Invalid credentials" });\n});', language: 'javascript', risk_level: 'high', status: 'pending' },
    { title: 'File Upload Endpoint', description: 'Check for file upload risks', code_snippet: 'app.post("/upload", (req, res) => {\n  const file = req.files.file;\n  file.mv(`./uploads/${file.name}`, (err) => {\n    if (err) return res.status(500).send(err);\n    res.send("File uploaded");\n  });\n});', language: 'javascript', risk_level: 'high', status: 'completed', vulnerabilities: 'Path traversal vulnerability. No file type validation. No size limits.', recommendations: 'Validate file types, sanitize filenames, add size limits, store outside webroot.' },
    { title: 'Session Management', description: 'Review session handling', code_snippet: 'app.use(session({\n  secret: "mysecret",\n  resave: false,\n  saveUninitialized: true,\n  cookie: { secure: false }\n}));', language: 'javascript', risk_level: 'medium', status: 'pending' },
    { title: 'Password Storage', description: 'Check password handling', code_snippet: 'const createUser = (email, password) => {\n  const hashedPassword = md5(password);\n  return db.insert({ email, password: hashedPassword });\n};', language: 'javascript', risk_level: 'critical', status: 'completed', vulnerabilities: 'MD5 is cryptographically broken. No salt used for password hashing.', recommendations: 'Use bcrypt, argon2, or scrypt with proper salt rounds.' },
    { title: 'API Key Handling', description: 'Review API key security', code_snippet: 'const API_KEY = "sk_live_abc123";\nconst fetchData = async () => {\n  const res = await fetch(url, { headers: { "X-API-Key": API_KEY } });\n  return res.json();\n};', language: 'javascript', risk_level: 'high', status: 'pending' },
    { title: 'CORS Configuration', description: 'Check CORS settings', code_snippet: 'app.use(cors({\n  origin: "*",\n  credentials: true\n}));', language: 'javascript', risk_level: 'medium', status: 'completed', vulnerabilities: 'Wildcard CORS with credentials enabled allows any origin to make authenticated requests.', recommendations: 'Specify allowed origins explicitly. Never use * with credentials.' },
    { title: 'JWT Implementation', description: 'Review token security', code_snippet: 'const generateToken = (user) => {\n  return jwt.sign(user, "secret123");\n};\nconst verifyToken = (token) => {\n  return jwt.verify(token, "secret123");\n};', language: 'javascript', risk_level: 'high', status: 'pending' },
    { title: 'HTML Rendering', description: 'Check for XSS vulnerabilities', code_snippet: 'app.get("/profile", (req, res) => {\n  const name = req.query.name;\n  res.send(`<h1>Hello, ${name}!</h1>`);\n});', language: 'javascript', risk_level: 'critical', status: 'completed', vulnerabilities: 'Reflected XSS vulnerability. User input rendered directly in HTML.', recommendations: 'Escape HTML entities. Use templating engines with auto-escaping.' },
    { title: 'Database Connection', description: 'Review DB security', code_snippet: 'const db = mysql.createConnection({\n  host: "localhost",\n  user: "root",\n  password: "",\n  database: "app"\n});', language: 'javascript', risk_level: 'medium', status: 'pending' },
    { title: 'Command Execution', description: 'Check for command injection', code_snippet: 'app.get("/ping", (req, res) => {\n  const host = req.query.host;\n  exec(`ping -c 1 ${host}`, (err, stdout) => {\n    res.send(stdout);\n  });\n});', language: 'javascript', risk_level: 'critical', status: 'completed', vulnerabilities: 'Command injection vulnerability. Attacker can execute arbitrary commands.', recommendations: 'Never pass user input to shell commands. Use allowlists or safer APIs.' },
    { title: 'Error Handling', description: 'Review error exposure', code_snippet: 'app.use((err, req, res, next) => {\n  res.status(500).json({\n    error: err.message,\n    stack: err.stack,\n    query: req.query\n  });\n});', language: 'javascript', risk_level: 'medium', status: 'pending' },
    { title: 'Cookie Security', description: 'Check cookie settings', code_snippet: 'res.cookie("auth_token", token, {\n  httpOnly: false,\n  secure: false,\n  sameSite: "none"\n});', language: 'javascript', risk_level: 'high', status: 'completed', vulnerabilities: 'Auth cookie accessible via JavaScript, sent over HTTP, and vulnerable to CSRF.', recommendations: 'Set httpOnly: true, secure: true, sameSite: strict or lax.' },
    { title: 'Rate Limiting', description: 'Review DoS protection', code_snippet: 'app.post("/api/data", async (req, res) => {\n  const result = await heavyComputation(req.body);\n  res.json(result);\n});', language: 'javascript', risk_level: 'medium', status: 'pending' },
    { title: 'Redirect Handling', description: 'Check for open redirect', code_snippet: 'app.get("/redirect", (req, res) => {\n  const url = req.query.url;\n  res.redirect(url);\n});', language: 'javascript', risk_level: 'medium', status: 'completed', vulnerabilities: 'Open redirect vulnerability. Attacker can redirect users to malicious sites.', recommendations: 'Validate redirect URLs against an allowlist of trusted domains.' }
  ];

  for (const item of items) {
    await query(
      `INSERT INTO security_scans (title, description, code_snippet, language, risk_level, status, vulnerabilities, recommendations)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
      [item.title, item.description, item.code_snippet, item.language, item.risk_level, item.status, item.vulnerabilities || null, item.recommendations || null]
    );
  }
  console.log('Seeded security_scans');
};

const seedPerformanceReports = async () => {
  const items = [
    { title: 'Database Query Optimization', description: 'Analyze N+1 query pattern', code_snippet: 'const getUsers = async () => {\n  const users = await User.findAll();\n  for (const user of users) {\n    user.orders = await Order.findAll({ where: { userId: user.id } });\n  }\n  return users;\n};', language: 'javascript', performance_score: 35, status: 'completed', bottlenecks: 'N+1 query problem causing excessive database calls', optimization_suggestions: 'Use eager loading: User.findAll({ include: Order })' },
    { title: 'Array Processing', description: 'Review array operations', code_snippet: 'const processItems = (items) => {\n  let result = [];\n  for (let i = 0; i < items.length; i++) {\n    if (items[i].active) {\n      result = [...result, transform(items[i])];\n    }\n  }\n  return result;\n};', language: 'javascript', performance_score: 45, status: 'pending' },
    { title: 'React Component Rendering', description: 'Check unnecessary re-renders', code_snippet: 'const UserList = ({ users }) => {\n  const sorted = users.sort((a, b) => a.name.localeCompare(b.name));\n  return sorted.map(user => <UserCard key={user.id} user={user} />);\n};', language: 'javascript', performance_score: 50, status: 'completed', bottlenecks: 'Sorting on every render. Array mutation in render.', optimization_suggestions: 'Use useMemo for sorted array. Avoid mutating props.' },
    { title: 'API Response Handling', description: 'Review data fetching', code_snippet: 'useEffect(() => {\n  fetch("/api/data").then(r => r.json()).then(setData);\n  fetch("/api/stats").then(r => r.json()).then(setStats);\n  fetch("/api/config").then(r => r.json()).then(setConfig);\n}, []);', language: 'javascript', performance_score: 55, status: 'pending' },
    { title: 'String Concatenation', description: 'Analyze string operations', code_snippet: 'const buildReport = (items) => {\n  let html = "";\n  for (const item of items) {\n    html += `<div>${item.name}</div>`;\n  }\n  return html;\n};', language: 'javascript', performance_score: 60, status: 'completed', bottlenecks: 'String concatenation in loop creates new strings each iteration', optimization_suggestions: 'Use array join or template literals with map' },
    { title: 'Event Handler Optimization', description: 'Check event listener efficiency', code_snippet: 'const List = ({ items, onItemClick }) => {\n  return items.map(item => (\n    <div onClick={() => onItemClick(item.id)}>\n      {item.name}\n    </div>\n  ));\n};', language: 'javascript', performance_score: 65, status: 'pending' },
    { title: 'Memory Leak Detection', description: 'Review cleanup patterns', code_snippet: 'useEffect(() => {\n  const interval = setInterval(() => {\n    fetchData().then(setData);\n  }, 5000);\n}, []);', language: 'javascript', performance_score: 40, status: 'completed', bottlenecks: 'Missing cleanup function causes memory leak', optimization_suggestions: 'Return cleanup function: return () => clearInterval(interval)' },
    { title: 'Image Loading Strategy', description: 'Analyze image optimization', code_snippet: 'const Gallery = ({ images }) => {\n  return images.map(img => (\n    <img src={img.fullSizeUrl} alt={img.title} />\n  ));\n};', language: 'javascript', performance_score: 30, status: 'pending' },
    { title: 'Search Algorithm', description: 'Review search implementation', code_snippet: 'const search = (items, query) => {\n  return items.filter(item => \n    item.name.toLowerCase().includes(query.toLowerCase())\n  );\n};', language: 'javascript', performance_score: 70, status: 'completed', bottlenecks: 'Linear search on every keystroke', optimization_suggestions: 'Implement debouncing. Consider indexing for large datasets.' },
    { title: 'State Update Batching', description: 'Check state updates', code_snippet: 'const handleSubmit = async () => {\n  setLoading(true);\n  setError(null);\n  setData(null);\n  const result = await fetchData();\n  setData(result);\n  setLoading(false);\n};', language: 'javascript', performance_score: 75, status: 'pending' },
    { title: 'Recursive Function Analysis', description: 'Review recursion efficiency', code_snippet: 'const fibonacci = (n) => {\n  if (n <= 1) return n;\n  return fibonacci(n - 1) + fibonacci(n - 2);\n};', language: 'javascript', performance_score: 20, status: 'completed', bottlenecks: 'Exponential time complexity O(2^n)', optimization_suggestions: 'Use memoization or iterative approach for O(n)' },
    { title: 'DOM Manipulation', description: 'Analyze DOM operations', code_snippet: 'const updateList = (items) => {\n  const container = document.getElementById("list");\n  items.forEach(item => {\n    container.innerHTML += `<div>${item}</div>`;\n  });\n};', language: 'javascript', performance_score: 25, status: 'pending' },
    { title: 'Data Transformation Pipeline', description: 'Review data processing', code_snippet: 'const process = (data) => {\n  const filtered = data.filter(x => x.active);\n  const mapped = filtered.map(x => transform(x));\n  const sorted = mapped.sort((a, b) => a.value - b.value);\n  return sorted;\n};', language: 'javascript', performance_score: 80, status: 'completed', bottlenecks: 'Multiple array iterations', optimization_suggestions: 'Chain operations or use single reduce for better performance' },
    { title: 'WebSocket Message Handling', description: 'Check message processing', code_snippet: 'socket.on("message", (data) => {\n  const parsed = JSON.parse(data);\n  updateState(parsed);\n  saveToStorage(parsed);\n  notifyListeners(parsed);\n});', language: 'javascript', performance_score: 70, status: 'pending' },
    { title: 'Lazy Loading Implementation', description: 'Review code splitting', code_snippet: 'import Home from "./pages/Home";\nimport About from "./pages/About";\nimport Dashboard from "./pages/Dashboard";\nimport Settings from "./pages/Settings";', language: 'javascript', performance_score: 40, status: 'completed', bottlenecks: 'All pages loaded upfront increasing initial bundle size', optimization_suggestions: 'Use React.lazy() and Suspense for code splitting' }
  ];

  for (const item of items) {
    await query(
      `INSERT INTO performance_reports (title, description, code_snippet, language, performance_score, status, bottlenecks, optimization_suggestions)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
      [item.title, item.description, item.code_snippet, item.language, item.performance_score || null, item.status, item.bottlenecks || null, item.optimization_suggestions || null]
    );
  }
  console.log('Seeded performance_reports');
};

const seedTestGenerations = async () => {
  const items = [
    { title: 'User Registration Function', description: 'Generate tests for signup', source_code: 'async function registerUser(email, password, name) {\n  if (!email || !password) throw new Error("Missing fields");\n  if (password.length < 8) throw new Error("Password too short");\n  const exists = await User.findByEmail(email);\n  if (exists) throw new Error("Email taken");\n  return User.create({ email, password: hash(password), name });\n}', language: 'javascript', test_framework: 'Jest', coverage_estimate: 90, status: 'completed', generated_tests: 'describe("registerUser", () => {\n  it("should create user with valid input", async () => {...});\n  it("should throw if email missing", async () => {...});\n  it("should throw if password too short", async () => {...});\n  it("should throw if email exists", async () => {...});\n});' },
    { title: 'Shopping Cart Calculator', description: 'Generate cart tests', source_code: 'function calculateTotal(items, discount = 0) {\n  const subtotal = items.reduce((sum, item) => sum + item.price * item.qty, 0);\n  const discountAmount = subtotal * (discount / 100);\n  return subtotal - discountAmount;\n}', language: 'javascript', test_framework: 'Jest', coverage_estimate: 85, status: 'pending' },
    { title: 'Date Formatter Utility', description: 'Generate date tests', source_code: 'function formatDate(date, format) {\n  const d = new Date(date);\n  if (isNaN(d)) return "Invalid date";\n  return format\n    .replace("YYYY", d.getFullYear())\n    .replace("MM", String(d.getMonth() + 1).padStart(2, "0"))\n    .replace("DD", String(d.getDate()).padStart(2, "0"));\n}', language: 'javascript', test_framework: 'Jest', coverage_estimate: 95, status: 'completed', generated_tests: 'describe("formatDate", () => {\n  it("formats date correctly", () => {...});\n  it("handles invalid date", () => {...});\n  it("pads single digits", () => {...});\n});' },
    { title: 'Email Validator', description: 'Generate validation tests', source_code: 'function isValidEmail(email) {\n  if (!email || typeof email !== "string") return false;\n  const regex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\n  return regex.test(email);\n}', language: 'javascript', test_framework: 'Jest', coverage_estimate: 100, status: 'pending' },
    { title: 'Array Sorting Function', description: 'Generate sorting tests', source_code: 'function sortByProperty(arr, prop, order = "asc") {\n  return [...arr].sort((a, b) => {\n    if (order === "asc") return a[prop] > b[prop] ? 1 : -1;\n    return a[prop] < b[prop] ? 1 : -1;\n  });\n}', language: 'javascript', test_framework: 'Jest', coverage_estimate: 90, status: 'completed', generated_tests: 'describe("sortByProperty", () => {\n  it("sorts ascending by default", () => {...});\n  it("sorts descending when specified", () => {...});\n  it("does not mutate original array", () => {...});\n});' },
    { title: 'API Response Handler', description: 'Generate API tests', source_code: 'async function fetchUser(id) {\n  const response = await fetch(`/api/users/${id}`);\n  if (!response.ok) throw new Error("User not found");\n  return response.json();\n}', language: 'javascript', test_framework: 'Jest', coverage_estimate: 80, status: 'pending' },
    { title: 'Password Strength Checker', description: 'Generate password tests', source_code: 'function checkPasswordStrength(password) {\n  let score = 0;\n  if (password.length >= 8) score++;\n  if (/[A-Z]/.test(password)) score++;\n  if (/[0-9]/.test(password)) score++;\n  if (/[^A-Za-z0-9]/.test(password)) score++;\n  return ["weak", "fair", "good", "strong"][score] || "weak";\n}', language: 'javascript', test_framework: 'Jest', coverage_estimate: 100, status: 'completed', generated_tests: 'describe("checkPasswordStrength", () => {\n  it("returns weak for short password", () => {...});\n  it("returns strong for complex password", () => {...});\n  it("increments score for each criteria", () => {...});\n});' },
    { title: 'React Toggle Component', description: 'Generate component tests', source_code: 'function Toggle({ value, onChange }) {\n  return (\n    <button onClick={() => onChange(!value)}>\n      {value ? "On" : "Off"}\n    </button>\n  );\n}', language: 'javascript', test_framework: 'React Testing Library', coverage_estimate: 85, status: 'pending' },
    { title: 'URL Parser Utility', description: 'Generate URL tests', source_code: 'function parseQueryString(url) {\n  const params = {};\n  const queryString = url.split("?")[1];\n  if (!queryString) return params;\n  queryString.split("&").forEach(pair => {\n    const [key, value] = pair.split("=");\n    params[decodeURIComponent(key)] = decodeURIComponent(value || "");\n  });\n  return params;\n}', language: 'javascript', test_framework: 'Jest', coverage_estimate: 95, status: 'completed', generated_tests: 'describe("parseQueryString", () => {\n  it("parses query params correctly", () => {...});\n  it("handles URL without query", () => {...});\n  it("decodes URI components", () => {...});\n});' },
    { title: 'Debounce Function', description: 'Generate debounce tests', source_code: 'function debounce(fn, delay) {\n  let timer;\n  return function(...args) {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn.apply(this, args), delay);\n  };\n}', language: 'javascript', test_framework: 'Jest', coverage_estimate: 80, status: 'pending' },
    { title: 'LocalStorage Wrapper', description: 'Generate storage tests', source_code: 'const storage = {\n  get(key) {\n    const item = localStorage.getItem(key);\n    return item ? JSON.parse(item) : null;\n  },\n  set(key, value) {\n    localStorage.setItem(key, JSON.stringify(value));\n  },\n  remove(key) {\n    localStorage.removeItem(key);\n  }\n};', language: 'javascript', test_framework: 'Jest', coverage_estimate: 100, status: 'completed', generated_tests: 'describe("storage", () => {\n  it("stores and retrieves values", () => {...});\n  it("returns null for missing keys", () => {...});\n  it("removes items correctly", () => {...});\n});' },
    { title: 'Number Formatter', description: 'Generate format tests', source_code: 'function formatNumber(num, decimals = 2) {\n  if (typeof num !== "number" || isNaN(num)) return "0";\n  return num.toLocaleString("en-US", {\n    minimumFractionDigits: decimals,\n    maximumFractionDigits: decimals\n  });\n}', language: 'javascript', test_framework: 'Jest', coverage_estimate: 90, status: 'pending' },
    { title: 'Object Deep Clone', description: 'Generate clone tests', source_code: 'function deepClone(obj) {\n  if (obj === null || typeof obj !== "object") return obj;\n  if (Array.isArray(obj)) return obj.map(item => deepClone(item));\n  return Object.fromEntries(\n    Object.entries(obj).map(([k, v]) => [k, deepClone(v)])\n  );\n}', language: 'javascript', test_framework: 'Jest', coverage_estimate: 95, status: 'completed', generated_tests: 'describe("deepClone", () => {\n  it("clones primitive values", () => {...});\n  it("clones arrays deeply", () => {...});\n  it("clones nested objects", () => {...});\n  it("handles null values", () => {...});\n});' },
    { title: 'Event Emitter', description: 'Generate emitter tests', source_code: 'class EventEmitter {\n  constructor() { this.events = {}; }\n  on(event, fn) { (this.events[event] ||= []).push(fn); }\n  off(event, fn) { this.events[event] = this.events[event]?.filter(f => f !== fn); }\n  emit(event, ...args) { this.events[event]?.forEach(fn => fn(...args)); }\n}', language: 'javascript', test_framework: 'Jest', coverage_estimate: 100, status: 'pending' },
    { title: 'Retry Mechanism', description: 'Generate retry tests', source_code: 'async function retry(fn, maxAttempts = 3, delay = 1000) {\n  for (let i = 0; i < maxAttempts; i++) {\n    try { return await fn(); }\n    catch (e) {\n      if (i === maxAttempts - 1) throw e;\n      await new Promise(r => setTimeout(r, delay));\n    }\n  }\n}', language: 'javascript', test_framework: 'Jest', coverage_estimate: 85, status: 'completed', generated_tests: 'describe("retry", () => {\n  it("returns on first success", async () => {...});\n  it("retries on failure", async () => {...});\n  it("throws after max attempts", async () => {...});\n});' }
  ];

  for (const item of items) {
    await query(
      `INSERT INTO test_generations (title, description, source_code, language, test_framework, coverage_estimate, status, generated_tests)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
      [item.title, item.description, item.source_code, item.language, item.test_framework, item.coverage_estimate || null, item.status, item.generated_tests || null]
    );
  }
  console.log('Seeded test_generations');
};

const seedRefactoringSuggestions = async () => {
  const items = [
    { title: 'Callback Hell Refactoring', description: 'Convert callbacks to async/await', original_code: 'function getData(callback) {\n  fetchUser((err, user) => {\n    if (err) return callback(err);\n    fetchOrders(user.id, (err, orders) => {\n      if (err) return callback(err);\n      fetchPayments(orders[0].id, (err, payments) => {\n        callback(null, { user, orders, payments });\n      });\n    });\n  });\n}', language: 'javascript', improvement_type: 'Async/Await', status: 'completed', refactored_code: 'async function getData() {\n  const user = await fetchUser();\n  const orders = await fetchOrders(user.id);\n  const payments = await fetchPayments(orders[0].id);\n  return { user, orders, payments };\n}', rationale: 'Async/await provides cleaner, more readable asynchronous code.' },
    { title: 'Magic Numbers Extraction', description: 'Replace magic numbers with constants', original_code: 'function calculateDiscount(price, qty) {\n  if (qty > 10) return price * 0.85;\n  if (qty > 5) return price * 0.9;\n  if (qty > 2) return price * 0.95;\n  return price;\n}', language: 'javascript', improvement_type: 'Constants', status: 'pending' },
    { title: 'Extract Method Refactoring', description: 'Break down long function', original_code: 'function processOrder(order) {\n  let total = 0;\n  for (const item of order.items) {\n    total += item.price * item.qty;\n  }\n  const tax = total * 0.1;\n  const shipping = total > 100 ? 0 : 10;\n  const discount = order.coupon ? total * 0.05 : 0;\n  return { subtotal: total, tax, shipping, discount, total: total + tax + shipping - discount };\n}', language: 'javascript', improvement_type: 'Extract Method', status: 'completed', refactored_code: 'const calculateSubtotal = (items) => items.reduce((sum, item) => sum + item.price * item.qty, 0);\nconst calculateTax = (subtotal) => subtotal * TAX_RATE;\nconst calculateShipping = (subtotal) => subtotal > FREE_SHIPPING_THRESHOLD ? 0 : SHIPPING_COST;\nconst calculateDiscount = (subtotal, coupon) => coupon ? subtotal * COUPON_DISCOUNT : 0;\n\nfunction processOrder(order) {\n  const subtotal = calculateSubtotal(order.items);\n  return {\n    subtotal,\n    tax: calculateTax(subtotal),\n    shipping: calculateShipping(subtotal),\n    discount: calculateDiscount(subtotal, order.coupon),\n    total: subtotal + calculateTax(subtotal) + calculateShipping(subtotal) - calculateDiscount(subtotal, order.coupon)\n  };\n}', rationale: 'Smaller, focused functions are easier to test and maintain.' },
    { title: 'Replace Conditional with Polymorphism', description: 'Use strategy pattern', original_code: 'function calculateArea(shape) {\n  if (shape.type === "circle") {\n    return Math.PI * shape.radius ** 2;\n  } else if (shape.type === "rectangle") {\n    return shape.width * shape.height;\n  } else if (shape.type === "triangle") {\n    return 0.5 * shape.base * shape.height;\n  }\n}', language: 'javascript', improvement_type: 'Design Pattern', status: 'pending' },
    { title: 'Guard Clauses', description: 'Replace nested conditionals', original_code: 'function getPaymentStatus(user) {\n  if (user) {\n    if (user.subscription) {\n      if (user.subscription.active) {\n        if (user.subscription.paid) {\n          return "active";\n        } else {\n          return "pending_payment";\n        }\n      } else {\n        return "expired";\n      }\n    } else {\n      return "no_subscription";\n    }\n  } else {\n    return "no_user";\n  }\n}', language: 'javascript', improvement_type: 'Guard Clauses', status: 'completed', refactored_code: 'function getPaymentStatus(user) {\n  if (!user) return "no_user";\n  if (!user.subscription) return "no_subscription";\n  if (!user.subscription.active) return "expired";\n  if (!user.subscription.paid) return "pending_payment";\n  return "active";\n}', rationale: 'Guard clauses reduce nesting and improve readability.' },
    { title: 'Object Destructuring', description: 'Use modern destructuring', original_code: 'function displayUser(user) {\n  const name = user.name;\n  const email = user.email;\n  const age = user.age;\n  const address = user.address.street + ", " + user.address.city;\n  return name + " (" + email + ") - " + age + " years old - " + address;\n}', language: 'javascript', improvement_type: 'ES6 Syntax', status: 'pending' },
    { title: 'Replace Loop with Higher-Order Functions', description: 'Use map/filter/reduce', original_code: 'function getActiveUserEmails(users) {\n  const result = [];\n  for (let i = 0; i < users.length; i++) {\n    if (users[i].active === true) {\n      result.push(users[i].email);\n    }\n  }\n  return result;\n}', language: 'javascript', improvement_type: 'Functional', status: 'completed', refactored_code: 'const getActiveUserEmails = (users) =>\n  users\n    .filter(user => user.active)\n    .map(user => user.email);', rationale: 'Functional methods are more declarative and less error-prone.' },
    { title: 'Null Object Pattern', description: 'Handle null cases elegantly', original_code: 'function getDiscount(customer) {\n  if (customer !== null && customer !== undefined) {\n    if (customer.membership !== null) {\n      if (customer.membership.level === "gold") {\n        return 0.2;\n      }\n    }\n  }\n  return 0;\n}', language: 'javascript', improvement_type: 'Design Pattern', status: 'pending' },
    { title: 'Template Literals', description: 'Replace string concatenation', original_code: 'function buildUrl(base, path, params) {\n  let url = base + "/" + path + "?";\n  const keys = Object.keys(params);\n  for (let i = 0; i < keys.length; i++) {\n    url += keys[i] + "=" + params[keys[i]];\n    if (i < keys.length - 1) url += "&";\n  }\n  return url;\n}', language: 'javascript', improvement_type: 'ES6 Syntax', status: 'completed', refactored_code: 'const buildUrl = (base, path, params) => {\n  const queryString = Object.entries(params)\n    .map(([key, value]) => `${encodeURIComponent(key)}=${encodeURIComponent(value)}`)\n    .join("&");\n  return `${base}/${path}?${queryString}`;\n};', rationale: 'Template literals and modern methods are cleaner and less error-prone.' },
    { title: 'Extract Configuration', description: 'Move hardcoded values to config', original_code: 'async function sendEmail(to, subject, body) {\n  const transporter = nodemailer.createTransport({\n    host: "smtp.gmail.com",\n    port: 587,\n    auth: {\n      user: "myapp@gmail.com",\n      pass: "supersecret123"\n    }\n  });\n  await transporter.sendMail({ from: "myapp@gmail.com", to, subject, html: body });\n}', language: 'javascript', improvement_type: 'Configuration', status: 'pending' },
    { title: 'Compose Functions', description: 'Use function composition', original_code: 'function processData(data) {\n  const validated = validate(data);\n  const normalized = normalize(validated);\n  const transformed = transform(normalized);\n  const formatted = format(transformed);\n  return formatted;\n}', language: 'javascript', improvement_type: 'Functional', status: 'completed', refactored_code: 'const pipe = (...fns) => (x) => fns.reduce((v, f) => f(v), x);\n\nconst processData = pipe(\n  validate,\n  normalize,\n  transform,\n  format\n);', rationale: 'Function composition creates a clear data transformation pipeline.' },
    { title: 'Replace Temp with Query', description: 'Extract expressions to methods', original_code: 'function getPrice(order) {\n  const basePrice = order.quantity * order.itemPrice;\n  const quantityDiscount = Math.max(0, order.quantity - 500) * order.itemPrice * 0.05;\n  const shipping = Math.min(basePrice * 0.1, 100);\n  return basePrice - quantityDiscount + shipping;\n}', language: 'javascript', improvement_type: 'Extract Method', status: 'pending' },
    { title: 'Introduce Parameter Object', description: 'Group related parameters', original_code: 'function createUser(firstName, lastName, email, street, city, zip, country, phone, birthDate) {\n  return {\n    name: firstName + " " + lastName,\n    email,\n    address: { street, city, zip, country },\n    phone,\n    birthDate\n  };\n}', language: 'javascript', improvement_type: 'Parameter Object', status: 'completed', refactored_code: 'function createUser({ name, email, address, phone, birthDate }) {\n  return {\n    name: `${name.first} ${name.last}`,\n    email,\n    address,\n    phone,\n    birthDate\n  };\n}\n\n// Usage:\ncreateUser({\n  name: { first: "John", last: "Doe" },\n  email: "john@example.com",\n  address: { street: "123 Main", city: "NYC", zip: "10001", country: "USA" },\n  phone: "555-1234",\n  birthDate: "1990-01-01"\n});', rationale: 'Parameter objects improve readability and make the API more flexible.' },
    { title: 'Replace Error Code with Exception', description: 'Use proper error handling', original_code: 'function withdraw(account, amount) {\n  if (amount <= 0) return -1;\n  if (account.balance < amount) return -2;\n  account.balance -= amount;\n  return 0;\n}', language: 'javascript', improvement_type: 'Error Handling', status: 'pending' },
    { title: 'Remove Duplicate Code', description: 'DRY principle application', original_code: 'function validateEmail(email) {\n  if (!email) return { valid: false, error: "Email required" };\n  if (!email.includes("@")) return { valid: false, error: "Invalid email" };\n  return { valid: true };\n}\n\nfunction validateUsername(username) {\n  if (!username) return { valid: false, error: "Username required" };\n  if (username.length < 3) return { valid: false, error: "Too short" };\n  return { valid: true };\n}', language: 'javascript', improvement_type: 'DRY', status: 'completed', refactored_code: 'const createValidator = (rules) => (value, fieldName) => {\n  for (const rule of rules) {\n    const error = rule(value, fieldName);\n    if (error) return { valid: false, error };\n  }\n  return { valid: true };\n};\n\nconst required = (value, field) => !value && `${field} required`;\nconst minLength = (min) => (value, field) => value?.length < min && `${field} too short`;\nconst isEmail = (value) => !value?.includes("@") && "Invalid email";\n\nconst validateEmail = createValidator([required, isEmail]);\nconst validateUsername = createValidator([required, minLength(3)]);', rationale: 'Reusable validator factory eliminates duplication and is extensible.' }
  ];

  for (const item of items) {
    await query(
      `INSERT INTO refactoring_suggestions (title, description, original_code, language, improvement_type, status, refactored_code, rationale)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
      [item.title, item.description, item.original_code, item.language, item.improvement_type, item.status, item.refactored_code || null, item.rationale || null]
    );
  }
  console.log('Seeded refactoring_suggestions');
};

const runSeed = async () => {
  try {
    console.log('Starting database seed...');

    // Initialize database tables
    await initDatabase();

    // Clear existing data
    const tables = [
      'code_reviews', 'documentation', 'code_analysis', 'api_docs',
      'readme_projects', 'code_comments', 'security_scans',
      'performance_reports', 'test_generations', 'refactoring_suggestions'
    ];

    for (const table of tables) {
      await query(`TRUNCATE TABLE ${table} RESTART IDENTITY CASCADE`);
    }
    console.log('Cleared existing data');

    // Seed all tables
    await seedCodeReviews();
    await seedDocumentation();
    await seedCodeAnalysis();
    await seedApiDocs();
    await seedReadmeProjects();
    await seedCodeComments();
    await seedSecurityScans();
    await seedPerformanceReports();
    await seedTestGenerations();
    await seedRefactoringSuggestions();

    console.log('Database seeding completed successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

runSeed();
