import crypto from 'crypto';
const transitions = { source_registered: ['ingesting'], ingesting: ['indexed', 'failed'], indexed: ['querying', 'retired', 'ingesting'], querying: ['answered', 'abstained', 'failed'], answered: ['feedback', 'querying'], abstained: ['feedback', 'querying'], feedback: ['querying'], failed: ['retrying'], retrying: ['ingesting'], retired: [] };
const perms = { viewer: ['read'], contributor: ['read', 'ingest', 'feedback'], reviewer: ['read', 'ingest', 'feedback', 'approve'], admin: ['read', 'ingest', 'feedback', 'approve', 'configure', 'delete'] };
const canonical=value=>Array.isArray(value)?value.map(canonical):value&&typeof value==='object'?Object.keys(value).sort().reduce((out,key)=>{out[key]=canonical(value[key]);return out;},{}):value;
export const hash = value => crypto.createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex');
export function requireScope(actor, tenantId, action, documentPermissions = []) { if (!actor || actor.tenantId !== tenantId) throw new Error('tenant_scope_denied'); if (!(perms[actor.role] || []).includes(action)) throw new Error('role_scope_denied'); if (documentPermissions.length && !documentPermissions.some(p => (actor.groups || []).includes(p) || actor.id === p)) throw new Error('document_scope_denied'); }
export function validateSource(source) { for (const f of ['sourceId', 'repository', 'commitSha', 'path', 'contentChecksum', 'parserVersion', 'permissions']) if (source[f] === undefined || source[f] === null || source[f] === '') throw new Error(`missing_${f}`); if (!Array.isArray(source.permissions) || !source.permissions.length) throw new Error('source_permissions_required'); return { ...source, sourceVersion: hash({ repository: source.repository, commitSha: source.commitSha, path: source.path, contentChecksum: source.contentChecksum }), state: 'source_registered' }; }
export function transition(current, target, context = {}) { if (!(transitions[current] || []).includes(target)) throw new Error('invalid_transition'); if (target === 'indexed' && (!context.chunkCount || !context.indexReceiptId)) throw new Error('index_receipt_required'); if (target === 'answered' && !context.answerEvaluation?.accepted) throw new Error('accepted_answer_evaluation_required'); return target; }
export function evaluateAnswer(answer, evidence, thresholds) { const metrics=['faithfulness','retrievalRecall','freshness'];for(const name of metrics)if(!Number.isFinite(answer[name])||answer[name]<0||answer[name]>1)throw new Error(`invalid_${name}`);for(const name of metrics)if(!Number.isFinite(thresholds[name])||thresholds[name]<0||thresholds[name]>1)throw new Error(`invalid_${name}_threshold`);const citations = answer.citations || []; const resolved = citations.length > 0 && citations.every(c => evidence.some(e => e.sourceVersion === c.sourceVersion && e.chunkId === c.chunkId)); const failures = []; if (!resolved) failures.push('citation_resolution'); if (answer.faithfulness < thresholds.faithfulness) failures.push('faithfulness'); if (answer.retrievalRecall < thresholds.retrievalRecall) failures.push('retrieval_recall'); if (answer.freshness < thresholds.freshness) failures.push('freshness'); if (answer.injectionDetected && !answer.abstained) failures.push('injection_resistance'); if (answer.conflictDetected && !answer.disclosedConflict) failures.push('conflict_disclosure'); return { accepted: !failures.length, shouldAbstain: failures.length > 0, failures, evaluationHash: hash({ answer, evidence, thresholds }) }; }
export function indexDelivery(provider, payload, idempotencyKey, receipt) { if (!provider || !idempotencyKey) throw new Error('delivery_identity_required'); const payloadHash = hash(payload); if (receipt && receipt.payloadHash !== payloadHash) throw new Error('receipt_payload_mismatch'); return { provider, payloadHash, idempotencyKey, state: receipt ? 'confirmed' : 'queued' }; }
export function deletionPropagation(sourceVersion, targets) { if (!sourceVersion || !Array.isArray(targets) || !targets.length) throw new Error('deletion_targets_required'); return targets.sort().map(target => ({ target, idempotencyKey: hash({ sourceVersion, target, operation: 'delete' }), state: 'queued' })); }
